# ุฏู "ุงุณู ุงููุฑุญ" ุงููู ููุธูุฑูู ูู ูุงุฆูุฉ ุงูู Actions
name: run cucumber tests

# ุฏู "ุณุงุนุฉ ุงูุตูุฑ": ุงูุชู ุงูุฑูุจูุช ุฏู ูุตุญู ููุดุชุบูุ
on:
  push:
    branches: ["master"] # ููุง ุญุฏ ูุนูู (Push) ููุฑูุน ููุฏ ุฌุฏูุฏ ุนูู ูุฑุน "master"

jobs:
  test:
    # ุฏู "ุฃุฑุถ ุงููุนุฑูุฉ": ุจูููู ูู GitHub ุฃุฌุฑููุง ุฌูุงุฒ ููุงุตูุงุชู ุฅููุ
    # ููุง ุทูุจูุง ุฌูุงุฒ "ูููุฏูุฒ" ุฃุญุฏุซ ุฅุตุฏุงุฑ (ุฒู ุฌูุงุฒู ุจุงูุธุจุท ุนุดุงู ูุชุชุนุจุด)
    runs-on: windows-latest

    steps:
      # ุงูุฎุทูุฉ 1: "ูุงุช ุงูุนุฏุฉ"
      # ุงูุฑูุจูุช ุจูุฑูุญ ุงููุฎุฒู (Repository) ููุณุญุจ ูุณุฎุฉ ูู ุงูููุฏ ุจุชุงุนู ูุญุทูุง ุนูู ุงูุฌูุงุฒ ุงููุคุฌุฑ
      - uses: actions/checkout@v3

      # ุงูุฎุทูุฉ 2: "ุฌูุฒ ุงูุนุฏุฉ"
      # ุจููููู ุณุทุจ Java 21 ุนุดุงู ุงูููุฏ ุจุชุงุนูุง ููุชูุจ ุจููุง
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          cache : maven        # ุงุญุชูุธ ุจุงูููุชุจุงุช ุนุดุงู ููุญูููุงุด ูู ูุฑุฉ (ุชูููุฑ ููุช)
          distribution: 'temurin' # ุฏู ููุน ูุดููุฑ ููุญุชุฑู ูู ุงูุฌุงูุง

      # ุงูุฎุทูุฉ 3: "ุฌูุฒ ุงูุนุฑุจูุฉ"
      # ุจููููู ุณุทุจ ูุชุตูุญ Google Chrome ุนุดุงู ุงูุณููููููู ูุนุฑู ููุชุญู
      - uses: browser-actions/setup-chrome@latest

      # ุงูุฎุทูุฉ 4: "ุฏูุณ ุจูุฒูู!" ๐๐จ
      # ุฏู ุฃูู ุฎุทูุฉุ ุจูุฑู ุฃูุฑ ุงููููู ุนุดุงู ูุจุฏุฃ ุงูุชุณุช ุงููุนูู
      - run: mvn clean test -Dbrowser="chrome"